Use only UniversalLink component and added download option passed to UniversalLink (#33)
* Use only UniversalLink component and added download option passed to UniversalLink

* i18n uses id instead of defaultMessage for value setting for schema fields :(

* fix(call-to-action): Widget when href value was an empty list

- In my sandbox I had a Call to action button that had this empty list value
  which crashed when edit page when block was focused
- Set id to same message as defaultMessage since apparently they need to be
  the same
- Removed undefined from defaultMessage of Target.
  When running make i18n it crashes due to it being called by plone/scripts
  This avoid the following error:
  node_modules/@plone/scripts/i18n.cjs:107
      `#. Default: "${messages[key].defaultMessage.trim()}"`,
  TypeError: Cannot read properties of undefined (reading 'trim')

* Added updated locales after make i18n ran from hook which replaces defaultMessage with default
 - This is happening due to plone/scripts since version 3.3